### ISSUE TITLE
game is bad

### ISSUE THREAD

**Issue by idkm23** [oplS17projects/Racket-League#1]
this game is so buggy and the devs are really unhelpful.
early access or not, i rate this game 2/10.

**Comment by infantinoalex** [comment]
Sorry we ran into a few development issues. We here at Racket-League Inc. are trying our best. If you have any serious issues with the game, don't hesitate to email infantinoalex@gmail.com. 

We would really like to know the exact issues that you are having.

We would be more than happy to issue you a free copy of the game if you'd be willing to give us a positive review on Steam Greenlight.

Thanks,

Dev Alex
